### ISSUE TITLE
Need some information for new UW properties to be used in RDA profile

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#1]
### I came up with some questions about our UW properties for propertyTemplates. Please [take a look at my questions are respond as you are able](https://docs.google.com/document/d/1YdEBhbwWOd8T9_wp3Rm5jW0GwZVPp240L8pul8t2H1I/edit?usp=sharing)--this will help to account for these properties in the schema.
(This document also linked to in OneDrive [here](https://uwnetid-my.sharepoint.com/:f:/r/personal/egrant2_uw_edu/Documents/LD4P2/BIBFRAME%20Profiles/UW%20Profiles?csf=1&e=ADsxMe)).

**Thank you!**
:pray:

**Comment by CECSpecialistI** [comment]
Looks like TG, AM and CC all responded (I did just now)

**Comment by briesenberg07** [comment]
**Thank you** everyone for commenting!
---
Proposals are in [the document](https://docs.google.com/document/d/1YdEBhbwWOd8T9_wp3Rm5jW0GwZVPp240L8pul8t2H1I/edit?usp=sharing) and have been incorporated into [the schema (v009base)](https://github.com/CECSpecialistI/UWLibCatProfiles/tree/master/uwSchemas/v009base).

Please provide additional feedback as necessary. 

It seems that I was confused about at least one thing: I had thought that YYYY-MM-DD was *always* included in **statusUw** values but it seems that this is not the case. The current schema (module [uw-property-template.json](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/e0ad483d093eca6fb140bad6ea48db0fd08a7002/uwSchemas/v009base/uw-property-template.json#L20)) currently enforces this but this could be rolled back, for example, if not useful.

Thanks again everyone--
