### ISSUE TITLE
New UW schema based on new Sinopia schema

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#10]
Current UW schema* is based on Sinopia schema v009. 

1) determine current Sinopia schema version conformance *and*
2) reproduce UW schema from this new Sinopia schema version *or*
3) make changes to existing UW schema reflecting updates in newer Sinopia schema

*For RDA profile, to account for local props needed to facilitate creation of format-specific profiles, etc.

**Comment by briesenberg07** [comment]
@CECSpecialistI 
@alexiskeely 

*I am still ignorant about what Sinopia schema version should be used to validate before upload to Sinopia nowadays. Do either or you know? Is it the newest (0.2.1)?*

The ETD profile I output today validated with v009, and uploaded fine (or so it seemed to me), so maybe this isn't a pressing issue.
But still, it seems like before too long we'll need to 1) revamp the UW schema based on a newer version and 2) change the `schema` values in our format-specific profiles.

**Comment by gerontakos** [comment]
I haven't kept up. Yes, at some point, their changes may require changes in our schema. If we can't figure it out, it will crash down on us -- but it won't be fatal I believe!

**Comment by briesenberg07** [comment]
**ALSO**
Add new prop `subtype` to schema for PTs.

**Comment by briesenberg07** [comment]
I'm officially making this a TO-DO for myself. Will use Sinopia schema v0.2.1 as base.

**Comment by briesenberg07** [comment]
Closing issue for now - per @briesenberg07 and @gerontakos discussion a new UW schema to validate UW master RDA profile is currently low priority for LD4P2 work.
---
**NOTE** that current UW schema (based on Sinopia schema v0.0.9) is referenced in master RDA profile, so even though it is out-of-date, removing it from this repo, etc., might cause additional problems when editing the profile in oXygen or another environment that checks against referenced profile.
