### ISSUE TITLE
Literal props that will be lookup props

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#11]
UW RDA profile currently has PTs with `type` `literal` that will change to `type` `lookup` pending future QA work.
These PTs include values for `useValuesFrom` and `defaultURI` etc. that will be needed for future lookups but will cause errors if output for literal-type PTs now.

**Comment by briesenberg07** [comment]
dvdVideo transform does not include [these changes](https://github.com/CECSpecialistI/UWLibCatProfiles/commit/f9c883668676c1d29eccc0879a004fe5fee17c8c#r34721963). Do they need to be added?

**Comment by gerontakos** [comment]
Hmm, looks like it but I'm not 100% sure. Talk about it Wednesday?

**Comment by briesenberg07** [comment]
Most recent mono transform 7d2a4cd3fe709a1654f9bfbcadef5410631b90d9 eliminates errors for unacceptable props in PTs with type `literal`.

**Comment by briesenberg07** [comment]
Preventing `valueTemplateRefs` from coming through to a profile for PTs with type `literal` is currently done **[here](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/d13c858478878af7cc020b8ec6780e02e7e4c608/scripts/jsonxml2formats.xsl#L161)** in L161 of the format-profile transform.
