### ISSUE TITLE
Duplicate defaultURI, defaultLiteral

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#13]
### has mode of issuance (RDA 2.13)

From **WAU.profile.RDA.json** :
```
"defaults": [
                      {
                          "defaultURI": "http://rdaregistry.info/termList/ModeIssue/1001",
                          "defaultLiteral": "single unit"
                      },
                      {
                          "defaultURI": "https://id.loc.gov/vocabulary/issuance/mono",
                          "defaultLiteral": "single unit"
                      }
                  ]
```

This PT has default values, leading to **duplicate keys and invalid JSON in output mono profile** (even though keys in these separate objects in the RDA profile are not duplicate).

Unless these duplicate default values are essential, the best course may be to fix the values in RDA profile.

**Comment by briesenberg07** [comment]
WHOOPS 
These are all XSLT problems--closing this issue.

**Comment by CECSpecialistI** [comment]
Is the problem with multiple defaultLiterals with the same value, or having defaults at all? Rather than using separate keys for either kind of default, do we need to put in multiple values into one key with commas in between?

**Comment by briesenberg07** [comment]
Should have said, **closed** this because *mode of issuance* now has:
```
"defaults": [
                        {
                            "defaultURI": "http://rdaregistry.info/termList/ModeIssue/1001",
                            "defaultLiteral": "single unit"
                        }
                    ]
```
