### ISSUE TITLE
Clear old scripts

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#16]
**I don't think we need:**

- json2xml-localFiles.xsl
- pipe2-formats.xsl (I should check once more to make sure this isn't called from the new `...-all.xsl` or `...-core.xsl`, but I don't think it is...)
- xml2json.xsl

**The following is only needed to output JSON-in-XML for RDA profile only for further transformation into HTML:**

- json2xml.xsl

**Comment by briesenberg07** [comment]
@gerontakos I'll get rid of unneeded scripts soon; confirming first

**DELETE**
- xml2json.xsl
- pipe2-formats.xsl
- json2xml-localfiles.xsl

**KEEP**
- append-uw-rda-profile.xsl
- rdaProps2Profile-v02.xsl
   - These were used to create the base template for our RDA profile, I believe (?)
   - They may be of value as new resources are added to the RDA registry, and we need to add these new resources to our source and/or format profiles, etc.
   - They may be of value to others wishing to build RDA profiles
- formatSpecificProfiles-all.xsl
- formatSpecificProfiles-core.xsl
   - These are currently used to generate format profiles
- jsonXmlProfile2HtmlProfile.xsl
   - Currently used to generate HTML profiles
   - Rename
- json2xml.xsl
   - Currently used to create a JSON-in-XML version of the source RDA profile (this is only needed for the generation of an HTML version of this source profile)

**Comment by gerontakos** [comment]
Top 3 in your list can be deleted, yes. If we're deleting, why keep anything but formatSpecificProfiles-all.xsl, jsonXmlProfile2HtmlProfile.xsl and json2xml.xsl? Aren't those the only ones we use? If we want to resuscitate any scripts, pull them out of an old commit?

**Comment by briesenberg07** [comment]
I think the scripts directory is in pretty good shape for the time being.
