### ISSUE TITLE
Requesting transfer of ownership of UWLibCatProfiles to uwlib-cams

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#20]
BMR will provide @CECSpecialistI an invite to become a member of the [uwlib-cams](https://github.com/uwlib-cams) organization. CEC should then be able to transfer ownership of the repo to uwlib-cams.

**Comment by CECSpecialistI** [comment]
done

**Comment by briesenberg07** [comment]
Thank you @CECSpecialistI !
