### ISSUE TITLE
Search out and assess use of datatype properties

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#21]
- Why did we put these in? 
- Should we keep them?

Important to consider given upcoming efforts to update RDA source profile.

Thank @mcm104 for pointing this out to us again!

**Comment by CECSpecialistI** [comment]
Might be good to check with Sinopia developers on this one...this wasn't being used previously because it wasn't working. An idea just popped into my brain though: Since new RDA is soooooooo specific regarding ranges for properties, we could fill these in in our big profile, and check Sinopia and make a decision for our cataloging input profiles based on that. I am fairly certain that "datatype" means it expects values to be examples of a certain class. But I can check on that right now.

**Comment by CECSpecialistI** [comment]
Typing for literals. See this LD4P2 issue: https://github.com/LD4P/sinopia_profile_editor/issues/239
It might be good for us to talk about it a little more, LD4 is saying their implementation doesn't conform to the BIBFRAME profiles spec: https://www.loc.gov/bibframe/docs/bibframe-profiles.html 

Name | valueDataType
-- | --
Description specifying a datatype for a literal.
Sub-description
None

Long story short: This would be useful for typing literals. Dates come to mind...it would be good to be able to type edtf dates as such. But, it doesn't look like Sinopia supports it yet. So, we can start doing typing of literal properties in the big profile if we want (I vote yes, but we'd have to investigate a little further how to format them and change the spec accordingly maybe), or we can ignore it for now and address it once there's a system that can implement it.

**Comment by briesenberg07** [comment]
Thank you for taking a look at this @CECSpecialistI \:

I do want to consider use of the `valueDataType` key in our Sinopia profiles going forward. Interesting to note that we only use this in our adminMetadata profile and nowhere else! The validation feature in [the issue you referenced](https://github.com/LD4P/sinopia_profile_editor/issues/239) would be pretty cool.

`valueDataType` is one of many Sinopia profile features that we have not yet used and might want to take advantage of in future, including some that seem to have been added to more recent versions of the schema. For example, did you know that options for property template `"type"` now include `"literal-lang"`, `"target"` (which I don't understand yet), and `"list"`? I didn't, until relatively recently. My first step in the "source/derivative profiles remodel project" is to take a closer look at the [newest schema](https://github.com/LD4P/sinopia/tree/master/schemas/0.2.1) and see what we could use to make things work better.

**BUT** actually this issue is regarding something different.

This is regarding the fact that we have just a few of the RDA datatype properties scattered throughout our profiles. Like, for example, [here](https://uwlib-cams.github.io/webviews/rdaprofiles/WAU.profile.RDA.eSerial.html#hasnoteontitleRDA2.17.2) with **has note on title** and **has note on frequency**. The overwhelming number of our RDA properties are *not* datatype (or object) properties. Although, of course, both are available in the Registry if we wanted to use them (for example [work datatype props](http://www.rdaregistry.info/Elements/w/datatype/) and [work object props](http://www.rdaregistry.info/Elements/w/object/)).

We just noticed these and couldn't remember how they got there. Was there a reason that we needed datatype properties for these few cases? Should we keep them there in future versions? Should we use more of them? Etc. 

I created this issue to remind myself and @gerontakos to take a closer look at some point. Hasn't happened yet. *But, do you remember how these got into the profiles?* Maybe you are the key to the mystery!

**Comment by gerontakos** [comment]
There are only 4 such properties and it appears to be 4 errors to me. The specific RDA datatype properties that we used do not even seem to exist. They are all, in their "regular" properties (ie neither dataype or object subproperties), manifestation properties and all of them expect Literal values. They're all note fields I believe. I think it's just something to correct. We did consider RDA datatype subproperties when we anticipated one use of the property with IRI values and another use of the same property with Literal values -- as with subjects: rdaw:P10256 for subjects with URI values, rdaw/datatype:P10256 for subjects with Literal values; for example, in the latter case, when an LCSH precoordinated heading never got assigned a URI and, in the former case, when the precoordinated heading did in fact get an IRI assigned. Best I can do for now.

**Comment by briesenberg07** [comment]
Thank you for taking a look @gerontakos !
Sounds like we may not need these in the next iteration of RDA Sinopia RTs.
The question of how to enforce constraints (encourage adherence to constraints?) on property values in Sinopia is an interesting one. Maybe someday there will be validation functionality, but it seems that the best we'll be able to do for the time being is to provide guidance for Sinopia data-entry where we are looking for values of a particular type.

**Comment by briesenberg07** [comment]
We did some checking, we are at least a bit better-informed when making property-use choices in future!
Thanks for weighing in everyone!
