### ISSUE TITLE
Output monograph profile v.4+, dvdVideo profile v.1

### ISSUE THREAD

**Issue by briesenberg07** [CECSpecialistI/UWLibCatProfiles#8]
### Goal: Output a monographs profile that validates with Sinopia v009 schema

Based on identification of problems, make any required changes to [jsonxml2monographs.xsl](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/master/scripts/jsonxml2monographs.xsl) and output monographs profile v05 (filename should be *WAU.profile.RDA.Monograph.v05.json*).

Validation issues with v04 can be reported here.

**Comment by briesenberg07** [comment]
@gerontakos 
### RE: transform(s) for new `monograph` and `dvdVideo` profiles

#### Questions/Notes Part I

- What Sinopia schema version to specify for [profile](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/60d1c072a477de38ac404a680bb5a1f6c7313569/scripts/jsonxml2monographs.xsl#L35) and [RTs](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/60d1c072a477de38ac404a680bb5a1f6c7313569/scripts/jsonxml2monographs.xsl#L68)?
- [RTs to bring into each profile](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/60d1c072a477de38ac404a680bb5a1f6c7313569/scripts/jsonxml2monographs.xsl#L46):
   - Are we bringing in Agent RT? It still has multiple values for **resourceURI**.
   - Nomen, Place, Timespan still in development and should not yet be brought in to format-specific profiles?
   - Note: Capitalize RT name components in [`@select`](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/60d1c072a477de38ac404a680bb5a1f6c7313569/scripts/jsonxml2monographs.xsl#L46) (*matches()* regex case-sensitive)
- **Note**: We identified earlier that before transforming the JSON-in-XML profile, it was necessary to undo any formatting and indenting that had been used in the meantime (*select all* > *right-click* > *Source* > *Join and Normalize Lines*) to avoid line breaks in JSON strings in the end product

...

**Comment by briesenberg07** [comment]
@gerontakos 
#### Questions/Notes Part II (of ?)
- [Is it possible to create both profiles with one transform](https://uwcams.slack.com/archives/GJ7KM73UP/p1564007992005400)? Or even if it is, would it save time and energy to just use two? If simply adapting a second XSLT to create `dvdVideo` is advisable I can start on this now.

**Comment by mchildsuw** [comment]
For profile generation, it would be great if we could create a test for empty values. They keep sneaking into the RDA profile..

**Comment by alexiskeely** [comment]
Weird: has jurisdiction governed (RDA 18.5). Property URI was not transferred from the RDA profile into the mono profile.

**Comment by gerontakos** [comment]
Amazing you noticed.
The property is incorrect in that case because there is a colon inside the quotation marks:
"propertyURI:": "http://rdaregistry.info/Elements/w/P10018 "
I believe that must have been someone inserting a colon by accident? Whatever the case, we'll need to repair manually in the RDA Profile!

**Comment by briesenberg07** [comment]
@gerontakos 
@alexiskeely 
@CECSpecialistI 
@mcm104 

I'm closing this issue as:
- a new mono profile has been output
- an initial dvdVideo profile has been output
- I *believe* the problem with RDA 18.5 has been addressed
- it (the issue) is not very specific and kind of all over the place

Also, **I made [some labels](https://github.com/CECSpecialistI/UWLibCatProfiles/labels) for use with issues in future! Please use and/or make more!**
