### ISSUE TITLE
RDA vs id.loc lookups

### ISSUE THREAD

**Issue by alexiskeely** [CECSpecialistI/UWLibCatProfiles#9]
QA does not currently support lookups to the rdaregistry vocabularies. Use of unsupported lookups results in non-functioning PTs within the profiles.

Affected lookup PTs:

Work:
- has color content of representative expression
- content type

Expression:
- has colour content
- content type
- has script
- has form of tactile notation

Manifestation:
- media type 
- carrier type 
- extent of manifestation 
- has base material
- has applied material
- has mount 
- has production method
- has generation 
- has layout 
- has bibliographic format 
- has font size 
- has note on extent of manifestation

**Comment by alexiskeely** [comment]
RDA registry vocabs are are in process for QA. Lookups have been temporarily switched to literal until they're ready in QA. Affected property templates have status:UW "attention RDA".

**Comment by alexiskeely** [comment]
@CECSpecialistI 

PTs with RDAregistry vocabs break preview RDF and _possibly_ template loading as well.

To replicate: open Expression:monograph and attempt to preview RDF.
workaround: remove PT has content type (RDA 6.9), and attempt to preview RDF

BUT:

Adminmetadata source of cataloging does not prevent RDF preview from working. Unclear

**Comment by alexiskeely** [comment]
@briesenberg07 
May have something to do with different default value representations in BF:bflc and format specific profiles.

edit: confirmed that the issue stems from default array structure. Defaults must align with the BF:bflc example below, and not Expression:monograph.

Expression:monographs:
 "defaults": [
                                {"defaultURI": "http://rdaregistry.info/termList/RDAContentType/1020"},
                                {"defaultLiteral": "text"}
                            ]

BF:bflc:
"defaults": [
                                {
                                    "defaultURI": "https://id.loc.gov/vocabulary/organizations/wau",
                                    "defaultLiteral": "WAU"
                                }

**Comment by briesenberg07** [comment]
Thank you for looking into this @alexiskeely .

Taking this as the bottom line...

> Defaults must align with the BF:bflc example below, and not Expression:monograph.

...the `defaults` array structure *could* be fixed in the transform from **WAU.profile.RDA** to **WAU.profile.RDA.monograph**, but it seems better to fix the array structure in the RDA profile itself. 

Seems like I should be able to do this in the RDA profile fairly easily with XSLT.

I will proceed with fixing the RDA master profile unless I hear differently.

**Comment by briesenberg07** [comment]
BTW strange to say, but the RDA `defaults` array structure *does* match the BF.BFLC structure in **seven places** (!?), such as:
```
{
        "propertyLabel": "has mode of issuance (RDA 2.13)",
        "propertyURI": "http://rdaregistry.info/Elements/m/P30003",
        "mandatory": "false",
        "repeatable": "false",
        "type": "lookup",
        "valueConstraint": {
            "useValuesFrom": ["http://rdaregistry.info/termList/ModeIssue"],
                    "valueDataType": {"dataTypeURI": ""},
                    "defaults": [
                        {
                            "defaultURI": "http://rdaregistry.info/termList/ModeIssue/1001",
                            "defaultLiteral": "single unit"
                        }
                    ]
                },
```
etc.

**Comment by CECSpecialistI** [comment]
Thanks for being willing to fix this, Ben, and for doing all that work to identify the issue, Alexis and Ben. Looks like there is no work left for me to do here, which pleases me :)

**Comment by CECSpecialistI** [comment]
Hah, that is strange! But makes sense. We've been messing around with those a lot by hand.

**Comment by alexiskeely** [comment]
> but the RDA `defaults` array structure

@briesenberg07 , is that in the mono profile, or in the master RDA? My version of mono still has the problematic structure:

```
`{
                        "propertyLabel": "has mode of issuance (RDA 2.13)",
                        "propertyURI": "http://rdaregistry.info/Elements/m/P30003",
                        "mandatory": "false",
                        "repeatable": "false",
                        "type": "lookup",
                        "remark": "http://access.rdatoolkit.org/2.13.html",
                        "valueConstraint": {
                            "useValuesFrom": ["http://rdaregistry.info/termList/ModeIssue"],
                            "defaults": [
                                {"defaultURI": "http://rdaregistry.info/termList/ModeIssue/1001"},
                                {"defaultLiteral": "single unit"}
                            ]
                        }
                    },`
```

**Comment by briesenberg07** [comment]
That's in the master RDA profile. I don't think any of the seven anomalous/correct `default` array structures ended up coming through to the mono profile.

> > but the RDA `defaults` array structure
> 
> @briesenberg07 , is that in the mono profile, or in the master RDA? My version of mono still has the problematic structure:
> 
> ```
> `{
>                 "propertyLabel": "has mode of issuance (RDA 2.13)",
>                 "propertyURI": "http://rdaregistry.info/Elements/m/P30003",
>                 "mandatory": "false",
>                 "repeatable": "false",
>                 "type": "lookup",
>                 "remark": "http://access.rdatoolkit.org/2.13.html",
>                 "valueConstraint": {
>                     "useValuesFrom": ["http://rdaregistry.info/termList/ModeIssue"],
>                     "defaults": [
>                         {"defaultURI": "http://rdaregistry.info/termList/ModeIssue/1001"},
>                         {"defaultLiteral": "single unit"}
>                     ]
>                 }
>             },`
> ```

**Comment by briesenberg07** [comment]
Fixed `defaults` array issues:
ddc1d7f44b402ce4f4e7c3af3a4412a4a201a748
*Closing*

**Comment by briesenberg07** [comment]
ACK!
![image](https://user-images.githubusercontent.com/27664966/65288159-b1223900-dafa-11e9-9de8-7ace77f04d07.png)
*Just saw the following change in the mono profile output from new RDA profile! ~How!?~ *
Problem seems to be [here](https://github.com/CECSpecialistI/UWLibCatProfiles/blob/ddc1d7f44b402ce4f4e7c3af3a4412a4a201a748/scripts/jsonxml2formats.xsl#L142) in format profile transform. Will fix.
**Keeping issue open for right now.**
